[workspace]
channels = ["conda-forge"]
name = "spotify-analysis"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.1,<3"
ipykernel = ">=6.29.5,<7"
requests = ">=2.32.4,<3"
scikit-learn = ">=1.7.1,<2"
hvplot = ">=0.11.3,<0.12"
umap-learn = ">=0.5.9.post2,<0.6"
numpy = "==2.2"
matplotlib = ">=3.10.3,<4"
datashader = ">=0.18.1,<0.19"
bokeh = ">=3.7.3,<4"
holoviews = ">=1.21.0,<2"
colorcet = ">=3.1.0,<4"
scikit-image = ">=0.25.2,<0.26"
jupyter_bokeh = ">=4.0.5,<5"
