[workspace]
channels = ["conda-forge"]
name = "spotify-analysis"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
pandas = ">=2.3.1,<3"
ipykernel = ">=6.29.5,<7"
